language: r
warnings_are_errors: true
sudo: true
env:
- NOT_CRAN=true
r:
- devel
r_binary_packages:
- rgdal
- sp
- rgeos
r_packages:
- formatR
- devtools
- raster
notifications:
  email:
    on_success: change
    on_failure: change
r_github_packages:
- jimhester/covr
after_success:
- Rscript -e 'library(covr); coveralls()'
before_install:
- openssl aes-256-cbc -K $encrypted_a40264e7df56_key -iv $encrypted_a40264e7df56_iv
  -in tests/testthat/key_file.rds.enc -out tests/testthat/key_file.rds -d
