name: Bug Test

on:
  push:
    branches: main

jobs:
  bug-test:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macos-latest, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/latest"}
          - {os: macos-10.15, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/latest"}
      
    steps:
      - name: checkout repo    
        uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          
      - name: Install gdal
        if: matrix.config.os != 'windows-latest'
        run: |
          brew install gdal proj
          
      - name: Install R packages
        run: |
          Rscript -e "install.packages('sf', configure.args = '--with-proj-lib=/usr/local/lib/', dependencies = TRUE)"
          Rscript -e "install.packages('rgdal', configure.args = c('--with-proj-lib=/usr/local/lib/', '--with-proj-include=/usr/local/include/'), dependencies = TRUE)"
          Rscript -e "install.packages(c(dplyr', 'elevatr', 'sp'), type = 'binary', dependencies = TRUE)"
          
      - name: Run bug code
        run: |
          Rscript -e "source('inst/bug.R')"
          